group: travis_latest
dist: jammy
language: python
cache: pip
python:
    - "3.10"
matrix:
    allow_failures:
        - python: nightly
        - python: pypy
        - python: pypy3
install:
    #- pip install -r requirements.txt
    - pip install flake8  # pytest  # add another testing frameworks later
before_script:
    - flake8 . --count --ignore=W504 --max-line-length=127 --show-source --statistics --exclude=./venv
script:
    - true  # pytest --capture=sys  # add others tests here
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down